name: doc

# event type（此处我们选择 push，且仅当 push 到 master 分支触发）
on:
  push:
    branches:
      - master

# 任务列表
jobs:
  # 任务名称
  release:
    # 在何种平台执行，可选 windows-latest/ubuntu-latest/macOS-latest 等
    runs-on: ubuntu-latest
    # 这里定义了任务运行过程中的各个步骤
    steps:
      - uses: actions/checkout@v2
      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: generate doc
        run: |
          yarn install --ignore-engines
          npx lerna bootstrap
          npm run build
          rm -rf .github && rm -rf .storybook && rm -rf packages
      - name: push doc
        run: |
          git config --global user.email "gmfe4code@163.com"
          git config --global user.name "gmfe4code"
          git add --all
          git commit -m 'build docs'
          ls
          git push 'https://gmfe4code:${{secrets.PASSWORD}}@github.com/gmfe/gm-mobile-docs.git' master:master -f